/**
 * NBA 隊伍
 */
export const nbaTeams = [
  { key: 'ATL', nameEn: 'Atlanta Hawks' },
  { key: 'BKN', nameEn: 'Brooklyn Nets' },
  { key: 'BOS', nameEn: 'Boston Celtics' },
  { key: 'CHA', nameEn: 'Charlotte Hornets' },
  { key: 'CHI', nameEn: 'Chicago Bulls' },
  { key: 'CLE', nameEn: 'Cleveland Cavaliers' },
  { key: 'DAL', nameEn: 'Dallas Mavericks' },
  { key: 'DEN', nameEn: 'Denver Nuggets' },
  { key: 'DET', nameEn: 'Detroit Pistons' },
  { key: 'GSW', nameEn: 'Golden State Warriors' },
  { key: 'HOU', nameEn: 'Houston Rockets' },
  { key: 'IND', nameEn: 'Indiana Pacers' },
  { key: 'LAC', nameEn: 'Los Angeles Clippers' },
  { key: 'LAL', nameEn: 'Los Angeles Lakers' },
  { key: 'MEM', nameEn: 'Memphis Grizzlies' },
  { key: 'MIA', nameEn: 'Miami Heat' },
  { key: 'MIL', nameEn: 'Milwaukee Bucks' },
  { key: 'MIN', nameEn: 'Minnesota Timberwolves' },
  { key: 'NOP', nameEn: 'New Orleans Pelicans' },
  { key: 'NYK', nameEn: 'New York Knicks' },
  { key: 'OKC', nameEn: 'Oklahoma City Thunder' },
  { key: 'ORL', nameEn: 'Orlando Magic' },
  { key: 'PHI', nameEn: 'Philadelphia 76ers' },
  { key: 'PHX', nameEn: 'Phoenix Suns' },
  { key: 'POR', nameEn: 'Portland Trail Blazers' },
  { key: 'SAC', nameEn: 'Sacramento Kings' },
  { key: 'SAS', nameEn: 'San Antonio Spurs' },
  { key: 'TOR', nameEn: 'Toronto Raptors' },
  { key: 'UTA', nameEn: 'Utah Jazz' },
  { key: 'WAS', nameEn: 'Washington Wizards' }
];
